### ISSUE TITLE
Home Page - Hero Section - Add some catchy phrases

### ISSUE THREAD

**Issue by VaclavElias** [stride3d/stride-website#117]
From Discord @jkao

jkao — Today at 18:29
I mean, I dont know is it just my though but this hero section it may look a little bit off, because usually hero has title like i dunno "stride engine", content text (i.e catchy phrase or something like you have mentioned in monogame website) and optionaly - buttons. And our hero section has only buttons ;-;

**Comment by jibranabsarulislam** [comment]
hey!

i can add a couple of tweaks to the hero section. i'll throw something together and link a PR

**Comment by VaclavElias** [comment]
That was quick, let me have a look :)

**Comment by VaclavElias** [comment]
Is it easy to work with 11ty?

**Comment by jibranabsarulislam** [comment]
> Is it easy to work with 11ty?

for the scope of this change, I think it was easy.

I'll be honest; didn't see that it was an 11ty project 😅; i saw the syntax `{% include somepage.html %}` and it reminded me of react components, how the contents of one file can be used/reused via the include syntax

**Comment by VaclavElias** [comment]
That is good. At least it was tested independently. Thank you @jibranabsarulislam. Your update is now published.

**Comment by jibranabsarulislam** [comment]
great, thanks @VaclavElias, although I don't think the styles made it to https://www.stride3d.net/. 
![image](https://github.com/stride3d/stride-website/assets/70596906/a2bf8da8-db26-4b6c-9240-03ed35784d7f)
![image](https://github.com/stride3d/stride-website/assets/70596906/09de87c9-5c60-40a5-a03a-895d055c0401)

**Comment by VaclavElias** [comment]
It might be a cache. Try to refresh? Also, we use Azure CDN, so depends where you are it might take some time to sync?

This is me in London 

![image](https://github.com/stride3d/stride-website/assets/4528464/a17ce733-045b-42d8-9dff-79ae16d7d374)

**Comment by jibranabsarulislam** [comment]
ah gotcha, must just be me then. I'll check back later and write if it hasn't changed.

my friend in Texas got it to display properly:

![image](https://github.com/stride3d/stride-website/assets/70596906/eb5ee830-acb1-4fae-befa-0934144a1411)

**Comment by VaclavElias** [comment]
We can actually force the css refresh by changing the website version which I did now. Good reminder!

**Comment by VaclavElias** [comment]
@jibranabsarulislam I had to update your PR with Bootstrap version (less css) which has inbuilt caption. My apology that I didn't mention that.

**Comment by jibranabsarulislam** [comment]
@VaclavElias 🫢 gotcha, i'm sorry about that!

that makes sense, i noticed some elements used bootstrap classes but i also noticed defined styles. I see how the changes have been converted; thank you for the fix!

**Comment by VaclavElias** [comment]
👍team work, collaboration, design and prototyping and (re)implementation 🤣. Thank you for going ahead with this.
