### ISSUE TITLE
Optimize Website Performance: Convert Large Images to WebP Format

### ISSUE THREAD

**Issue by VaclavElias** [stride3d/stride-website#126]
In an effort to optimize the performance of the Stride website, we should consider converting our large-sized images to the WebP format. WebP images provide superior lossless and lossy compression for images on the web, reducing the load time and improving the user experience.

This task will involve identifying large images that are currently in formats like JPEG or PNG and converting them to WebP without compromising the image quality.

**Comment by NicusorN5** [comment]
How much of a performance gain is using WebP instead of high res PNGs for example?

**Comment by parhamgholami** [comment]
Does this still need volunteers? I could try taking a crack at this on the weekend if we need folks to convert the images.

**Comment by VaclavElias** [comment]
Maybe top 10 or 20 biggest images?

We can keep the resolution the same, just conversion to **webp** should reduce the size. Also, when I do it, I double check visually that the image doesn't get blurry, as in some cases high res are important to show up 🙂.

We don't need to be sophisticated, having multiple resolutions for different screen sizes..

If you change anything to **webp**, make sure you update accordingly the `.md` or `.html` file which is referencing the image.

Thanks.

![image](https://github.com/stride3d/stride-website/assets/4528464/6748501f-1d30-49c9-afa9-b764baafb768)

**Comment by parhamgholami** [comment]
Sounds good! I'll start working on this over the coming days. 😄

**Comment by parhamgholami** [comment]
Following up on this: the top 20 images that are accessible from the site have been converted to WebP, along with the files referencing them. Should I remove the original PNGs and JPGs or leave them alone?

**Comment by VaclavElias** [comment]
Thank you @parhamgholami. Please remove them, you can create PR and I will test it also myself 🙂

**Comment by parhamgholami** [comment]
Sounds good! Created the PR 😄

**Comment by VaclavElias** [comment]
Hi @parhamgholami,

I checked all closely because I wasn't sure if the images are going to be ok. Your update will save almost **7MB**.

Except this image **stride-game-engine-default-og.webp**, I think all is ok. 

Would you be ok to reverse the change on this image **stride-game-engine-default-og.webp** and update the path back in `_head.html`? The reason is that image has some dot mesh/tiny squares, or whatever it is and when converted to webp, it doesn't look that great as the original. I forgot I was trying to do it myself and it didn't work, whatever webp settings I set. 

Or I can merge your PR and I can correct it afterwards. 

Let me know. Thank you very much otherwise! 🙂

**Comment by parhamgholami** [comment]
@VaclavElias No problem at all! I'll revert the stride-game-engine-default-og.webp related changes shortly.

**Comment by parhamgholami** [comment]
@VaclavElias All set! 😄

**Comment by VaclavElias** [comment]
Closing this issue as resolved.

PR #179 

Thank you @parhamgholami
