### ISSUE TITLE
Missing page in manual hierarchy

### ISSUE THREAD

**Issue by Doprez** [stride3d/stride-website#138]
[this video page](https://doc.stride3d.net/latest/en/manual/video/video-scripts.md) exists in the hierarchy in the manual but gives a missing page error when trying to access.

![image](https://github.com/stride3d/stride-website/assets/73259914/7fc20241-8261-4e97-9070-560edfee2b40)

**Comment by VaclavElias** [comment]
It is removed in the new docs.. I got such instructions. 

<img width="277" alt="image" src="https://github.com/stride3d/stride-website/assets/4528464/3384aa09-d037-4b28-b1e4-3ea0b08d04fc">

**Comment by VaclavElias** [comment]
Closing as the link was removed.
