### ISSUE TITLE
Home Page - Second Video - Update YouTube Title

### ISSUE THREAD

**Issue by VaclavElias** [stride3d/stride-website#152]
The second YouTube video shows a year 2017 which doesn't give a good impression on the website. Could it be something more generic?

We changed the title for the 1st video already but we forgot the 2nd one. 

https://www.youtube.com/watch?v=m4bC4h0aXfA

**Comment by chkworks** [comment]
I think this issue can be closed with the recent proposals?

**Comment by VaclavElias** [comment]
Yes. Thank you @chkworks.
