### ISSUE TITLE
Roadmap icon is still the Trello logo

### ISSUE THREAD

**Issue by StefanJanssen95** [stride3d/stride-website#26]
When I clicked on the roadmap on the [community page](https://stride3d.net/community/) I was surprised to go to the github project instead of a Trello board.

According to [Trello's Logo Guidelines](https://trello.com/about/logo):
> **Third-Party Guidelines**
If you’re using Trello in your third-party project, that’s awesome! Please feel free to do the following…
> - Use the Trello logo to link to Trello
> - Use the Trello logo to advertise that your product has built-in Trello integration
> - Use the Trello logo in a blog post or news article about Trello
>
> But please don’t…
> - Use Taco or the Trello logo for your application’s icon
> - Create a modified version of Taco or the Trello logo
> - Integrate Taco or the Trello logo into your logo
> - Change the colors, dimensions or add your own text/images
>
> Trello and the Trello logo are trademarked. Don’t use them to represent your product. Please don’t name your projects or domain names anything that implies Trello’s endorsement. Thanks!

I think the logo should be replaced for a non-branded alternative.

**Comment by VaclavElias** [comment]
This seems to be resolved, doesn't happen anymore?
