### ISSUE TITLE
[Forum] Can't login to https://forums.stride3d.net/ with github account

### ISSUE THREAD

**Issue by StefanJanssen95** [stride3d/stride-website#28]
As reported in: stride3d/stride#703
After being redirected back to 'https://forums.stride3d.net/auth/github/callback' it shows the error
> Sorry, there was an error authorizing your account. Please try again.

**Query String Parameters:**
error: redirect_uri_mismatch
error_description: The redirect_uri MUST match the registered callback URL for this application.
error_uri: https://developer.github.com/apps/managing-oauth-apps/troubleshooting-authorization-request-errors/#redirect-uri-mismatch
state: e6235c54c015dbb2ed9999adb00ebd9578fa3e8d2a6518df

**Comment by xen2** [comment]
Thanks for the report.
Can you give it another try please?

**Comment by StefanJanssen95** [comment]
It seems to be solved 👍
