### ISSUE TITLE
Top Navigation - Stride Logo disappears when the theme is Auto

### ISSUE THREAD

**Issue by VaclavElias** [stride3d/stride-website#76]
From: Joreyk

<img width="263" alt="image" src="https://github.com/stride3d/stride-website/assets/4528464/0902aaba-05b6-4c3c-bec2-5ea1297de153">

**Comment by NicusorN5** [comment]
This bug still exists in the blog page, but not the homepage.

**Comment by NicusorN5** [comment]
Oh yeah, sorry, refreshing worked.

**Comment by VaclavElias** [comment]
Caching has advantages but also disadvantages, so these specific bugs are rather caught before the new website is cached by everyone :) At least we know that **refresh** was working! Thank you @NicusorN5  for testing it for us!
