### ISSUE TITLE
Blog Post - Create a separate post about .NET Live

### ISSUE THREAD

**Issue by VaclavElias** [stride3d/stride-website#85]
This deservers a separate post https://www.youtube.com/watch?v=J6g5y8m26zs

@ykafia, would you like to help with this?

**Comment by ykafia** [comment]
Yes, I will try to work on it next week since I'll be on vacations

**Comment by VaclavElias** [comment]
Thank you, I will help with the content 🙂 and @tebjan can review and add his content part, because it is a new page, you don't need to do any chore related with installation process of the website, like in the current website, you can just create a new page in the `/post` folder and because we have got now staging env, you will be able to publish it to staging env 🙂

**Comment by VaclavElias** [comment]
I am closing this but @ykafia and @tebjan if you would like to add more content. Please go ahead.
